<?php

/**
 * Notification for different site URL
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
	exit;
}

?>

<div id="message" class="error ywsbs_different_url">
	<p>
		<strong><?php _e('YITH WooCommerce Subscription', 'yith-woocommerce-subscription'); ?></strong>
	</p>
	<p>
		<?php _e('Your site address has changed. Automatic payments and emails to customers have been disabled to
		prevent transactions generated by testing or staging servers.', 'yith-woocommerce-subscription'); ?><br />
		<?php _e('If you have moved this site to its permanent URL and you want to re-enable automatic payments and emails,
		please, select one of the following options', 'yith-woocommerce-subscription'); ?>
	</p>
	<form action="" method="post">
		<button class="button-primary" name="ywsbs_hide_different_site_url_warning" value="ignore"><?php _e('Hide this warning', 'yith-woocommerce-subscription'); ?></button>
		<button class="button" name="ywsbs_confirm_main_site_url" value="change"><?php _e('This is the main site URL', 'yith-woocommerce-subscription'); ?></button>
	</form>
</div>
