<?php

// autoload_static.php @generated by Composer

namespace AdvancedAdsPro\Autoload;

class ComposerStaticInit_advanced_ads_pro
{
    public static $classMap = array (
        'Advanced_Ads_Pro' => __DIR__ . '/../..' . '/classes/advanced-ads-pro.php',
        'Advanced_Ads_Pro_AdSense_Public' => __DIR__ . '/../..' . '/modules/gadsense/public.php',
        'Advanced_Ads_Pro_Admin' => __DIR__ . '/../..' . '/classes/advanced-ads-pro-admin.php',
        'Advanced_Ads_Pro_Cache_Busting_Server_Info' => __DIR__ . '/../..' . '/modules/cache-busting/server-info.class.php',
        'Advanced_Ads_Pro_Cache_Busting_Server_Info_Cookie' => __DIR__ . '/../..' . '/modules/cache-busting/server-info.class.php',
        'Advanced_Ads_Pro_Compatibility' => __DIR__ . '/../..' . '/classes/compatibility.php',
        'Advanced_Ads_Pro_Group_Refresh' => __DIR__ . '/../..' . '/modules/group-refresh/group-refresh.class.php',
        'Advanced_Ads_Pro_Group_Refresh_Admin' => __DIR__ . '/../..' . '/modules/group-refresh/admin.class.php',
        'Advanced_Ads_Pro_Module_Ad_Server' => __DIR__ . '/../..' . '/modules/ad-server/main.class.php',
        'Advanced_Ads_Pro_Module_Ad_Server_Admin' => __DIR__ . '/../..' . '/modules/ad-server/admin.class.php',
        'Advanced_Ads_Pro_Module_Admin_Bar' => __DIR__ . '/../..' . '/modules/admin-bar/admin-bar.class.php',
        'Advanced_Ads_Pro_Module_Ads_For_Adblockers' => __DIR__ . '/../..' . '/modules/ads-for-adblockers/main.class.php',
        'Advanced_Ads_Pro_Module_Ads_For_Adblockers_Admin' => __DIR__ . '/../..' . '/modules/ads-for-adblockers/admin.class.php',
        'Advanced_Ads_Pro_Module_Advanced_Display_Conditions' => __DIR__ . '/../..' . '/modules/advanced-display-conditions/main.class.php',
        'Advanced_Ads_Pro_Module_Advanced_Display_Conditions_Admin' => __DIR__ . '/../..' . '/modules/advanced-display-conditions/admin.class.php',
        'Advanced_Ads_Pro_Module_Advanced_Visitor_Conditions' => __DIR__ . '/../..' . '/modules/advanced-visitor-conditions/main.class.php',
        'Advanced_Ads_Pro_Module_Advanced_Visitor_Conditions_Admin' => __DIR__ . '/../..' . '/modules/advanced-visitor-conditions/admin.class.php',
        'Advanced_Ads_Pro_Module_Background_Ads' => __DIR__ . '/../..' . '/modules/background-ads/background.class.php',
        'Advanced_Ads_Pro_Module_Background_Ads_Admin' => __DIR__ . '/../..' . '/modules/background-ads/admin.class.php',
        'Advanced_Ads_Pro_Module_BuddyPress' => __DIR__ . '/../..' . '/modules/buddypress/buddypress.class.php',
        'Advanced_Ads_Pro_Module_BuddyPress_Admin' => __DIR__ . '/../..' . '/modules/buddypress/admin.class.php',
        'Advanced_Ads_Pro_Module_CFP' => __DIR__ . '/../..' . '/modules/click-fraud-protection/click-fraud-protection.class.php',
        'Advanced_Ads_Pro_Module_CFP_Admin' => __DIR__ . '/../..' . '/modules/click-fraud-protection/admin.class.php',
        'Advanced_Ads_Pro_Module_Cache_Busting' => __DIR__ . '/../..' . '/modules/cache-busting/cache-busting.class.php',
        'Advanced_Ads_Pro_Module_Cache_Busting_Admin' => __DIR__ . '/../..' . '/modules/cache-busting/admin.class.php',
        'Advanced_Ads_Pro_Module_Cache_Busting_Admin_UI' => __DIR__ . '/../..' . '/modules/cache-busting/admin-ui.class.php',
        'Advanced_Ads_Pro_Module_Duplicate_Ads' => __DIR__ . '/../..' . '/modules/duplicate-ads/duplicate.class.php',
        'Advanced_Ads_Pro_Module_Duplicate_Ads_Admin' => __DIR__ . '/../..' . '/modules/duplicate-ads/admin.class.php',
        'Advanced_Ads_Pro_Module_GamiPress' => __DIR__ . '/../..' . '/modules/gamipress/gamipress.class.php',
        'Advanced_Ads_Pro_Module_GamiPress_Admin' => __DIR__ . '/../..' . '/modules/gamipress/admin.class.php',
        'Advanced_Ads_Pro_Module_Grids' => __DIR__ . '/../..' . '/modules/grids/grids.class.php',
        'Advanced_Ads_Pro_Module_Grids_Admin' => __DIR__ . '/../..' . '/modules/grids/admin.class.php',
        'Advanced_Ads_Pro_Module_Inject_Content' => __DIR__ . '/../..' . '/modules/inject-content/inject-content.class.php',
        'Advanced_Ads_Pro_Module_Inject_Content_Admin' => __DIR__ . '/../..' . '/modules/inject-content/admin.class.php',
        'Advanced_Ads_Pro_Module_Lazy_Load_Admin' => __DIR__ . '/../..' . '/modules/lazy-load/admin.class.php',
        'Advanced_Ads_Pro_Module_PaidMembershipsPro' => __DIR__ . '/../..' . '/modules/paid-memberships-pro/main.class.php',
        'Advanced_Ads_Pro_Module_PaidMembershipsPro_Admin' => __DIR__ . '/../..' . '/modules/paid-memberships-pro/admin.class.php',
        'Advanced_Ads_Pro_Module_Placement_Conditions' => __DIR__ . '/../..' . '/modules/placement_conditions/main.class.php',
        'Advanced_Ads_Pro_Module_Placement_Conditions_Admin' => __DIR__ . '/../..' . '/modules/placement_conditions/admin.class.php',
        'Advanced_Ads_Pro_Module_bbPress' => __DIR__ . '/../..' . '/modules/bbpress/bbpress.class.php',
        'Advanced_Ads_Pro_Module_bbPress_Admin' => __DIR__ . '/../..' . '/modules/bbpress/admin.class.php',
        'Advanced_Ads_Pro_Offset_Shifter' => __DIR__ . '/../..' . '/classes/class-advanced-ads-pro-offset-shifter.php',
        'Advanced_Ads_Pro_Placement_Tests' => __DIR__ . '/../..' . '/modules/placement-tests/placement-tests.class.php',
        'Advanced_Ads_Pro_Utils' => __DIR__ . '/../..' . '/classes/utils.php',
        'Advanced_Ads_Pro_Weekdays' => __DIR__ . '/../..' . '/modules/weekdays/weekdays.class.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit_advanced_ads_pro::$classMap;

        }, null, ClassLoader::class);
    }
}
